
create table if not exists public.blessure_protocoles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  nom text not null,
  description text,
  paliers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.blessure_protocoles enable row level security;
drop policy if exists coach_all_blessure_protocoles on public.blessure_protocoles;
create policy coach_all_blessure_protocoles on public.blessure_protocoles for all using (is_coach());
drop policy if exists client_read_blessure_protocoles on public.blessure_protocoles;
create policy client_read_blessure_protocoles on public.blessure_protocoles for select using (true);

alter table public.joueur_blessures add column if not exists protocole_id uuid references public.blessure_protocoles(id);
alter table public.joueur_blessures add column if not exists tests_valides jsonb not null default '{}'::jsonb;

insert into public.blessure_protocoles (slug, nom, description, paliers) values
('entorse_cheville', 'Entorse de cheville', 'Ligaments latéraux de la cheville.', $j${"repos_total": {"description": "Décharge partielle si besoin, mobilisation précoce en amplitude non douloureuse, travail proprioceptif assis dès que possible.", "tests": []}, "course_seule": {"description": "Renforcement des fibulaires (élastique), équilibre unipodal yeux ouverts puis fermés, plan instable. Marche puis jogging rectiligne.", "tests": []}, "sans_contact": {"description": "Course progressive en intensité, changements de direction contrôlés, sauts bipodaux puis unipodaux, travail de vitesse.", "tests": []}, "entrainement_complet": {"description": "Réintégration du plaquage/regroupement, chevillère ou strapping de soutien si besoin les premières semaines.", "tests": [{"id": "t1", "nom": "Équilibre unipodal (Y-balance / SEBT)", "critere": "Symétrie ≥ 90% entre les deux jambes"}, {"id": "t2", "nom": "Hop test simple, triple, croisé, 6m chronométré", "critere": "LSI ≥ 90% par rapport au côté sain"}, {"id": "t3", "nom": "Course en huit (figure-8)", "critere": "Sans douleur, sans compensation visible"}, {"id": "t4", "nom": "505 test (changement de direction à haute vitesse)", "critere": "Temps ≤ 10% du temps pré-blessure"}]}}$j$::jsonb),
('lesion_musculaire', 'Lésion musculaire (ischio, quad, mollet, adducteurs)', 'Classification inspirée du British Athletics Muscle Injury Classification (BAMIC).', $j${"repos_total": {"description": "Contractions isométriques sous-douloureuses précoces, mobilité du tronc/bassin, vélo léger sans douleur.", "tests": []}, "course_seule": {"description": "Nordic hamstring progressif, pont fessier/leg curl excentrique, marche puis jogging à faible allure sans douleur.", "tests": []}, "sans_contact": {"description": "Montée progressive en vitesse de course (70 → 100% VMA), travail en longueur (Askling), changements de direction, accélérations/décélérations.", "tests": []}, "entrainement_complet": {"description": "Sprints répétés à vitesse maximale, gestes de contact, volume d'entraînement complet avant match.", "tests": [{"id": "t1", "nom": "Force isocinétique (ratio ischio/quad)", "critere": "LSI ≥ 90%, ratio dans la norme du joueur"}, {"id": "t2", "nom": "Nordic hamstring (force excentrique)", "critere": "Force symétrique, sans appréhension"}, {"id": "t3", "nom": "Askling H-test (souplesse active en longueur)", "critere": "Amplitude sans douleur, symétrique"}, {"id": "t4", "nom": "Sprint progressif 70/80/90/100%", "critere": "Aucune appréhension à vitesse maximale"}, {"id": "t5", "nom": "Saut horizontal (broad jump) / triple bond", "critere": "LSI ≥ 90%"}]}}$j$::jsonb),
('genou_lcm', 'Genou — entorse LCM', 'Ligament collatéral médial.', $j${"repos_total": {"description": "Contrôle de l'œdème, mobilisation en amplitude non douloureuse, activation du quadriceps.", "tests": []}, "course_seule": {"description": "Renforcement en chaîne fermée, proprioception, marche puis jogging rectiligne sans douleur.", "tests": []}, "sans_contact": {"description": "Course progressive, changements de direction sous-maximaux, renforcement en charge (squat, fentes).", "tests": []}, "entrainement_complet": {"description": "Réintégration du contact et des changements de direction à pleine intensité.", "tests": [{"id": "t1", "nom": "Test de laxité en valgus (0° et 30°)", "critere": "Stable, sans douleur"}, {"id": "t2", "nom": "Force quadriceps/ischio", "critere": "LSI ≥ 90%"}, {"id": "t3", "nom": "Hop tests (simple, triple, croisé, 6m)", "critere": "LSI ≥ 90%"}]}}$j$::jsonb),
('genou_lca', 'Genou — rupture LCA', 'Le plus souvent chirurgical (ligamentoplastie). Délai minimum 9 à 12 mois avant retour au contact — le temps seul n''est pas suffisant, la décision se fait sur les tests ET la préparation psychologique.', $j${"repos_total": {"description": "Récupération de l'extension complète en priorité, contrôle de l'œdème, marche sans boiterie, activation du quadriceps.", "tests": []}, "course_seule": {"description": "Chaîne fermée puis ouverte, proprioception, vélo/natation. Course en ligne droite dès accord médical (souvent ~12 semaines).", "tests": []}, "sans_contact": {"description": "Course progressive, pliométrie basique à avancée, changements de direction sous-maximaux, renforcement lourd (squat, fentes, soulevé).", "tests": []}, "entrainement_complet": {"description": "Vitesse maximale, changements de direction à pleine intensité, réintroduction très progressive du contact.", "tests": [{"id": "t1", "nom": "Force quadriceps/ischio (isocinétique)", "critere": "LSI ≥ 90% sur les deux groupes musculaires"}, {"id": "t2", "nom": "Batterie de hop tests (simple, triple, croisé, 6m)", "critere": "LSI ≥ 90% sur les 4 tests"}, {"id": "t3", "nom": "Questionnaire de préparation psychologique (type ACL-RSI)", "critere": "Score élevé de confiance"}, {"id": "t4", "nom": "Contrôle du valgus dynamique à la réception de saut", "critere": "Alignement genou-pied correct"}, {"id": "t5", "nom": "Changement de direction à vitesse maximale", "critere": "Comparable au côté sain, sans appréhension"}]}}$j$::jsonb),
('genou_menisque', 'Genou — lésion méniscale', 'Selon le type (stable/instable) et le traitement (conservateur, suture, méniscectomie).', $j${"repos_total": {"description": "Protection de la cicatrisation, flexion limitée les premières semaines si suture, contrôle de l'œdème.", "tests": []}, "course_seule": {"description": "Renforcement en chaîne fermée, proprioception, marche puis jogging sans torsion ni flexion profonde.", "tests": []}, "sans_contact": {"description": "Course progressive, changements de direction progressifs, attention à l'appui en flexion profonde et à la torsion.", "tests": []}, "entrainement_complet": {"description": "Réintégration du contact et des appuis en torsion à pleine intensité.", "tests": [{"id": "t1", "nom": "Amplitude complète sans douleur (flexion profonde)", "critere": "Symétrique, sans blocage"}, {"id": "t2", "nom": "Hop tests (simple, triple, croisé, 6m)", "critere": "LSI ≥ 90%"}, {"id": "t3", "nom": "Changement de direction avec torsion", "critere": "Sans douleur ni appréhension"}]}}$j$::jsonb),
('epaule', 'Épaule (AC, luxation, coiffe des rotateurs)', 'Entorse acromio-claviculaire, luxation gléno-humérale ou lésion de la coiffe.', $j${"repos_total": {"description": "Immobilisation courte si besoin (écharpe), mobilisation pendulaire précoce, isométrique sous-douloureux (rotateurs).", "tests": []}, "course_seule": {"description": "Chaîne cinétique de l'épaule (coiffe, scapula), élastique en rotation, gainage. Course autorisée.", "tests": []}, "sans_contact": {"description": "Renforcement en charge lourde, gestes techniques sans contact, pliométrie du haut du corps (medecine ball).", "tests": []}, "entrainement_complet": {"description": "Réintégration du plaquage en insistant sur la technique (épaule basse, tête placée), mêlée en dernier.", "tests": [{"id": "t1", "nom": "Force rotation interne/externe (dynamomètre)", "critere": "LSI ≥ 90%, ratio RE/RI dans la norme"}, {"id": "t2", "nom": "CKCUEST (stabilité chaîne fermée membre sup.)", "critere": "Nombre de touches symétrique"}, {"id": "t3", "nom": "Test d'appréhension / relocation", "critere": "Négatif"}, {"id": "t4", "nom": "Pompes plyométriques / lancer de medecine ball", "critere": "Puissance symétrique, sans douleur"}]}}$j$::jsonb),
('poignet_main', 'Poignet, main & doigts', 'Entorse, fracture du scaphoïde, luxation de doigt.', $j${"repos_total": {"description": "Immobilisation/protection selon gravité, glace, contrôle de la douleur.", "tests": []}, "course_seule": {"description": "Récupération d'amplitude articulaire, mobilisations douces.", "tests": []}, "sans_contact": {"description": "Renforcement de la préhension, gestes techniques (passe, réception) sans contact.", "tests": []}, "entrainement_complet": {"description": "Retour au jeu souvent protégé (attelle/strapping), réintégration du contact.", "tests": [{"id": "t1", "nom": "Force de préhension (dynamomètre)", "critere": "LSI ≥ 90%"}, {"id": "t2", "nom": "Amplitude articulaire complète", "critere": "Comparable au côté sain, sans douleur"}, {"id": "t3", "nom": "Réception de ballon à vitesse", "critere": "Sans appréhension ni douleur"}]}}$j$::jsonb),
('commotion', 'Commotion cérébrale', 'Graduated Return to Play (World Rugby), alignée sur le consensus international d''Amsterdam 2022. Chaque étape dure minimum 24h ; tout retour de symptôme fait reculer à l''étape précédente. Délai minimum réglementaire de 12 jours (niveau élite) avant le retour en match, sous validation d''un médecin formé à la commotion.', $j${"repos_total": {"description": "24–48h de repos physique et cognitif léger (pas d'écrans prolongés), puis activité légère de la vie quotidienne dès disparition des symptômes au repos.", "tests": []}, "course_seule": {"description": "Activité aérobie légère (marche/vélo, sans résistance) puis exercices sport-spécifique sans risque de choc à la tête (course, déplacements). Toujours sans contact.", "tests": []}, "sans_contact": {"description": "Entraînement plus complexe (passes, changements de direction), renforcement en charge, coordination — toujours sans aucun contact.", "tests": []}, "entrainement_complet": {"description": "Après feu vert médical, réintégration complète de l'entraînement incluant le contact.", "tests": [{"id": "t1", "nom": "Échelle de symptômes (type SCAT6)", "critere": "Retour à la ligne de base individuelle"}, {"id": "t2", "nom": "Tests cognitifs / équilibre (BESS ou équivalent)", "critere": "Retour à la normale"}, {"id": "t3", "nom": "Tolérance à l'effort progressif", "critere": "Aucun symptôme déclenché à chaque palier"}]}}$j$::jsonb),
('cervical', 'Rachis cervical (entorse / stinger)', 'Atteinte transitoire du plexus brachial (stinger) ou entorse cervicale simple.', $j${"repos_total": {"description": "Examen neurologique complet du membre supérieur (force, sensibilité, réflexes), écarter une atteinte structurelle.", "tests": []}, "course_seule": {"description": "Renforcement isométrique puis dynamique des fléchisseurs/extenseurs profonds du cou et de la ceinture scapulaire.", "tests": []}, "sans_contact": {"description": "Travail spécifique de force du cou en charge, gainage cervical.", "tests": []}, "entrainement_complet": {"description": "Travail technique du plaquage/mêlée (position de tête, engagement) avant réintégration en situation réelle.", "tests": [{"id": "t1", "nom": "Bilan neurologique complet du membre supérieur", "critere": "Force, sensibilité et réflexes normaux et symétriques"}, {"id": "t2", "nom": "Force isométrique du rachis cervical (4 directions)", "critere": "Retour au niveau pré-blessure"}, {"id": "t3", "nom": "Amplitude cervicale complète", "critere": "Sans douleur"}]}}$j$::jsonb),
('cotes_lombaires', 'Côtes & lombaires', 'Contusion/fracture costale ou lombalgie mécanique.', $j${"repos_total": {"description": "Contrôle de la douleur à la respiration profonde/toux (côtes) ou repos relatif (lombaires).", "tests": []}, "course_seule": {"description": "Reprise progressive de la mobilité, marche puis jogging léger sans douleur.", "tests": []}, "sans_contact": {"description": "Gainage, renforcement du tronc, rotation progressive en charge légère.", "tests": []}, "entrainement_complet": {"description": "Gilet de protection possible au retour au contact (côtes), réintégration du contact et de la mêlée.", "tests": [{"id": "t1", "nom": "Respiration profonde / toux sans douleur", "critere": "Indolore (côtes)"}, {"id": "t2", "nom": "Gainage (planche, side-plank) & mobilité lombaire", "critere": "Tenue symétrique, sans douleur"}, {"id": "t3", "nom": "Charge fonctionnelle (soulevé, rotation du tronc en charge)", "critere": "Technique correcte, charge proche du niveau pré-blessure"}]}}$j$::jsonb),
('fracture', 'Fracture', 'Délai lié à la consolidation osseuse, variable selon la zone.', $j${"repos_total": {"description": "Immobilisation selon prescription médicale, décharge stricte si besoin, contrôle de la douleur.", "tests": []}, "course_seule": {"description": "Reprise progressive de la mise en charge selon avis médical/radiologique, mobilité douce.", "tests": []}, "sans_contact": {"description": "Renforcement progressif, réathlétisation, course adaptée à la zone consolidée.", "tests": []}, "entrainement_complet": {"description": "Réintégration du contact seulement après consolidation confirmée et accord médical.", "tests": [{"id": "t1", "nom": "Confirmation de consolidation (imagerie)", "critere": "Validée par le médecin"}, {"id": "t2", "nom": "Force et amplitude de la zone concernée", "critere": "Comparable au côté sain"}]}}$j$::jsonb)
on conflict (slug) do nothing;
